[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
pico-args = "0.5.0"
serde_json = "1.0.66"
regex = "1.5.4"
num = "0.4.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
harness = false
name = "solutions"
